//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiZal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class przedmiot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public przedmiot()
        {
            this.zapis_przedmiotow = new HashSet<zapis_przedmiotow>();
        }
    
        public int id_przedmiotu { get; set; }
        public string przedmiot1 { get; set; }
        public Nullable<decimal> ETCS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zapis_przedmiotow> zapis_przedmiotow { get; set; }
    }
}
