//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiZal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zapis_przedmiotow
    {
        public int zapis_przedmiotu { get; set; }
        public Nullable<int> zapis_numer { get; set; }
        public Nullable<int> id_przedmiotu { get; set; }
    
        public virtual przedmiot przedmiot { get; set; }
        public virtual zapis zapis { get; set; }
    }
}
