//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiZal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zapis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zapis()
        {
            this.zapis_przedmiotow = new HashSet<zapis_przedmiotow>();
        }
    
        public int zapis_numer { get; set; }
        public Nullable<decimal> indeks { get; set; }
        public string kierunek { get; set; }
        public Nullable<decimal> Total_ETCS { get; set; }
    
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zapis_przedmiotow> zapis_przedmiotow { get; set; }
    }
}
